/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import aplicacion.Mensaje;

/**
 *
 * @author slimbbok
 */
public class Vcorreo extends javax.swing.JDialog {
    
    private aplicacion.FachadaAplicacion fa;
    private java.awt.Frame parent;
    private java.util.List<Mensaje> mensajes;
    /**
     * Creates new form Vcorreo
     */
    public Vcorreo(java.awt.Frame parent, boolean modal,aplicacion.FachadaAplicacion fa, java.util.List<Mensaje> mensajes) {
        super(parent, modal);
        this.fa=fa;
        this.parent=parent;
        initComponents();
        
        this.mensajes=mensajes;
        ModeloTablaMensajes mTablaMensajes = new ModeloTablaMensajes();
        tablaMensajes.setModel(mTablaMensajes);
        mTablaMensajes.setFilas(mensajes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMensajes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btlFiltarLeido = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        taMensaje = new javax.swing.JTextArea();
        btnResponder = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        txtFiltroEmisor = new javax.swing.JTextField();
        btnFiltrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFiltradoAsunto = new javax.swing.JTextField();
        btnNuevoMensaje = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaMensajes.setModel(new ModeloTablaMensajes());
        jScrollPane1.setViewportView(tablaMensajes);

        jLabel1.setText("Bandeja de Mensajes:");

        btlFiltarLeido.setText("Filtrar por Leído");

        taMensaje.setColumns(20);
        taMensaje.setRows(5);
        jScrollPane2.setViewportView(taMensaje);

        btnResponder.setText("Responder");

        btnConfirmar.setText("Confirmar");
        btnConfirmar.setEnabled(false);

        btnFiltrar.setText("Filtrar");

        jLabel2.setText("Emisor:");

        jLabel3.setText("Asunto:");

        btnNuevoMensaje.setText("Nuevo mensaje");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btlFiltarLeido)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtFiltroEmisor)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtFiltradoAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnFiltrar))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnNuevoMensaje)
                                    .addGap(27, 27, 27)
                                    .addComponent(btnResponder)
                                    .addGap(34, 34, 34)
                                    .addComponent(btnConfirmar))
                                .addComponent(jScrollPane2))
                            .addGap(19, 19, 19))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFiltradoAsunto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btlFiltarLeido)
                        .addComponent(jLabel2)
                        .addComponent(txtFiltroEmisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnFiltrar)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnResponder)
                            .addComponent(btnConfirmar)
                            .addComponent(btnNuevoMensaje)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btlFiltarLeido;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnNuevoMensaje;
    private javax.swing.JButton btnResponder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea taMensaje;
    private javax.swing.JTable tablaMensajes;
    private javax.swing.JTextField txtFiltradoAsunto;
    private javax.swing.JTextField txtFiltroEmisor;
    // End of variables declaration//GEN-END:variables
}
